version: "3"
services:
  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=Qwz.1201
  calf:
    image: blog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - "8088:8088"
    depends_on:
      - mysql