server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      eanbled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # MySQL database configuration.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: Qwz#1201

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  cache:
    type: none
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics','env','logfile','health' ]
logging:
  level:
    com.qinweizhao.blog: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
  file:
    path: ${halo.work-dir}/blog-resource/logs

springfox:
  documentation:
    enabled: true

halo:
  auth-enabled: true
  mode: development
  workDir: ${user.home}/Code/qwz/qwz-blog/
  cache: memory
  admin-path: qwz
