server:
  port: 8090
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  devtools:
    restart:
      eanbled: false
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
  profiles:
    active: dev
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
logging:
  level:
    com.qinweizhao.blog: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${halo.work-dir}/logs